name: image_transformer
version: 0.0.1
author: Oliver Sand <oliver.sand@tentaclelabs.com>
description: A Pub tranformer for converting between image formats.
homepage: https://github.com/Fox32/image_transformer
documentation: https://github.com/Fox32/image_transformer
dependencies:
  barback: any
  image: any
